version: "2.1"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: senao
      MYSQL_HOST: 127.0.0.1
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 5

  flask:
    container_name: flask
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../:/usr/src/senao
    depends_on:
      mysql:
        condition: service_healthy
    env_file: senao.env
    expose:
      - "8700"
    ports:
      - "8700:8700"
    command: uwsgi --ini /usr/src/senao/uwsgi.ini
    restart: always

  nginx:
    image: nginx:1.12
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - flask
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
      - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
